# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02e4dd0ffef49be4cfc1123d7ef4ab2142fa76b0cea3ee23fd0e18b9b955e3601fbfdeaa42905d3d139fd4a888ca2430061828adcaf781ddfa1b2c1abcc54616

test:
  secret_key_base: c8bea632c7db6699f7f4f7ae77ad16e52e3d5dea2918ebbcd3996d3acb2c3c13618bdde5748081c172af9f058df29ac3b571a04ac4e42243416e86fe99b282ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
